# Generated by Django 3.0.6 on 2020-05-30 22:01

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[account.validators.validate_email], verbose_name='email'),
        ),
    ]
