# Generated by Django 3.0.6 on 2020-06-05 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
