# Generated by Django 3.0.6 on 2020-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_offer_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('brak', 'brak'), ('praca - zatrudnie', 'praca - zatrudnie'), ('prace - poszukuje', 'prace - poszukuje'), ('elektronika - kupie', 'elektronika - kupie'), ('elektronika - sprzedam', 'elektronika - sprzedam')], default='brak', max_length=30),
        ),
    ]
