# Generated by Django 3.0.6 on 2020-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_auto_20200605_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='display_period',
            field=models.IntegerField(default=1),
        ),
    ]
