# Generated by Django 3.0.6 on 2020-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20200605_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
