# Generated by Django 3.0.6 on 2020-06-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_offer_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('praca - zatrudnie', 'praca - zatrudnie'), ('prace - poszukuje', 'prace - poszukuje'), ('elektronika - kupie', 'elektronika - kupie'), ('elektronika - sprzedam', 'elektronika - sprzedam'), ('usługi - zlece', 'usługi - zlece'), ('usługi - wykonam', 'usługi - wykonam'), ('dom - kupie', 'dom - kupie'), ('dom - sprzedam', 'dom - sprzedam')], max_length=30),
        ),
    ]
